version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: email_aggregator_db
    environment:
      POSTGRES_USER: email_user
      POSTGRES_PASSWORD: email_password
      POSTGRES_DB: email_aggregator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - email_network

  redis:
    image: redis:7-alpine
    container_name: email_aggregator_redis
    ports:
      - "6379:6379"
    networks:
      - email_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: email_aggregator_backend
    environment:
      DATABASE_URL: postgresql://email_user:email_password@postgres:5432/email_aggregator
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: your-secret-key-here-change-in-production
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      CORS_ORIGINS: http://localhost:3000
    ports:
      - "8080:8080"
      - "2525:2525"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - email_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: email_aggregator_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - email_network
    environment:
      - VITE_API_URL=http://localhost:8080

networks:
  email_network:
    driver: bridge

volumes:
  postgres_data: